### PR TITLE
tutorial revision

### PR DESCRIPTION
**Pull request by suitecake**
First revision of tutorial.
- Added Foreword
- Added Conclusion
- Added second vis (Exploratory Vis)
- Replaced header

### CODE REVIEW

**Comment by suitecake** [comment]
Also adjusted the Credits section; I wrote the initial draft of the tutorial, but Scott uploaded it for me to GitHub.

**Comment by suitecake** [comment]
NOTE: I updated the Python notebook with my text editor, not realizing that the information is duplicated in tutorial_pto.html. I'm not sure how these files are generated (whether the notebook is generated from the html, or vice-versa). tutorial_pto.html has not been updated in this PR

**Comment by suitecake** [comment]
What's the plan?

@sbeliveau336: Do you have write access?

**Comment by TanyaShen-BEA** [comment]
Not sure what you mean.  Would you like to explain more?

Thank you
Tanya

**Comment by sbeliveau336** [comment]
Think its been resolved @StarCYing merged the branch with the updates he asked for.

**Pull request merged**
